version: '3.8'

services:
  activemq:
    image: apache/activemq-classic:6.1.3
    container_name: activemq
    ports:
      - "61616:61616"   # JMS port
      - "8161:8161"     # Web Console port
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSCODE=passw0rd
    volumes:
      - activemq_data:/opt/apache-activemq/data
      - activemq_log:/opt/apache-activemq/data/log
    networks:
      - activemq_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  activemq_data:
    driver: local
  activemq_log:
    driver: local

networks:
  activemq_network:
    driver: bridge