server:
  port: 8084

spring:
  application:
    name: 'customer-service'

  cloud:
    stream:
      bindings:
        orderCreated-in-0:
          destination: order_created
        orderCharged-in-0:
          destination: order_charged
        orderNotCharged-in-0:
          destination: order_not_charged
        orderShipped-in-0:
          destination: order_shipped
        customerCreatedProducer-out-0:
          destination: customer_created
        customerUpdatedProducer-out-0:
          destination: customer_updated
        processOrderProducer-out-0:
          destination: process_order
      binders:
        default:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:localhost}
                port: 5672
                username: admin
                password: passw0rd

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

# logging settings
logging:
  level:
    root: info
    com: warn
    org:
      apache: warn
      hibernate: warn
      springframework: warn

  pattern:
    #console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'