server:
  port: 8082

spring:
  application:
    name: 'billing-service'

  cloud:
    stream:
      bindings:
        chargeOrder-in-0:
          destination: charge_order
        orderChargedProducer-out-0:
          destination: order_charged
      binders:
        default:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: passw0rd

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

# logging settings
logging:
  level:
    root: info
    com: warn
    org:
      apache: warn
      hibernate: warn
      springframework: warn

  pattern:
    #console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'